'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const model=require('../dist/catalog-model.js');const data=require('../dist/data.json');
const dataset={id:'fixture',label:'Official catalog'};
const source={product_detail_parsed:true,reference_number:'TEST-1',id:'test-1',captured_at:'2026-10-01T22:00:00Z',diameter:'40 mm',movement:'Self-winding',brand:'Fixture',specific_model:'Chronomat Automatic',description:'The manufacturer also makes chronographs and diamond watches.',crystal:'Sapphire crystal',jewels:'25'};
test('capture date uses the collection timezone and missing prices stay missing',()=>{const row=model.normalize(source,dataset);assert.equal(row.captured_date,'2026-10-02');assert.equal(row.price_value,null);assert.equal(row.movement_family,'Automatic');assert.equal(row.segment,'Time & date');assert.equal(row.gem_set,false);});
test('diagonal and multiple dimensions do not distort wristwatch diameter comparisons',()=>{const a=model.normalize({...source,diameter:'30 x 40 mm'},dataset),b=model.normalize({...source,case_dimensions_display:'Diagonal: 40 mm'},dataset);assert.equal(a.diameter_mm,null);assert.equal(b.diameter_metric_eligible,false);assert.equal(model.summarizeWatches([a,b],'test').diameterN,0);});
test('pocket watches remain in catalog counts and are excluded from wristwatch measurements',()=>{const row=model.normalize({...source,subtype:'Pocketwatch'},dataset);assert.equal(row.watch_kind,'Pocket watch');assert.equal(row.is_watch,true);assert.equal(model.summarizeWatches([row],'test').count,1);assert.equal(model.summarizeWatches([row],'test').diameterN,0);});
test('gemstone classification uses selected watch specifications',()=>{const row=model.normalize({...source,gem_setting:'Bezel set with 40 diamonds'},dataset);assert.equal(row.gem_set,true);assert.deepEqual(row.gemstones,['Diamond']);});
test('curated sorting retains new watchmakers and every reference',()=>{const rows=[{brand:'Old',id:1},{brand:'New',id:2},{brand:'Future',id:3},{brand:'New',id:4}];assert.deepEqual(model.curatedOrder(rows,['New','Old']).map(r=>r.id),[2,1,3,4]);});
test('imported catalogs preserve complete reference counts and pocket types',()=>{assert.equal(data.records.filter(r=>r.brand==='Patek Philippe'&&r.is_watch).length,252);assert.equal(data.records.filter(r=>r.brand==='Breitling'&&r.is_watch).length,402);assert.equal(data.records.filter(r=>r.brand==='Patek Philippe'&&r.watch_kind==='Pocket watch').length,20);});

test('Jaeger-LeCoultre and Omega imports match the completed exports',()=>{assert.equal(data.records.filter(r=>r.brand==='Jaeger-LeCoultre'&&r.is_watch).length,197);assert.equal(data.records.filter(r=>r.brand==='Omega'&&r.is_watch).length,556);assert.equal(data.records.filter(r=>r.brand==='Omega'&&r.watch_kind==='Pocket watch').length,3);});
test('missing images remain valid watch references with a catalog fallback',()=>{const row=model.normalize({...source,image_URL:'',brand:'Omega'},dataset);assert.equal(row.image_url,'');assert.equal(row.is_watch,true);});
