const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const source=fs.readFileSync(require.resolve('../dist/comparison.js'),'utf8');
const rows=Array.from({length:9},(_,i)=>({id:'watch-'+i,is_watch:true,brand:'Maker',specific_model:'Model',reference_number:'Ref-'+i,diameter:'40 mm',diameter_mm:40,extra_specs:[]}));
function workspace(storage=new Map()){
 const document={querySelector(){return null;},querySelectorAll(){return [];}};const localStorage={getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)};
 const ctx={document,localStorage,location:{hash:'#finder'},setTimeout:()=>0,clearTimeout(){},AtlasCompare:require('../dist/comparison-model.js'),AtlasModel:require('../dist/catalog-model.js')};ctx.globalThis=ctx;vm.createContext(ctx);vm.runInContext(source,ctx);return {api:ctx.AtlasWorkspace,storage};
}
test('finder and comparison share a persistent six-watch shortlist across partial bootstrap reloads',()=>{const first=workspace();first.api.initialize({partial:true,records:rows.slice(0,1)});first.api.upsert(rows);for(const row of rows)first.api.toggle(row.id);assert.equal(first.api.selectedIds().length,6);const reloaded=workspace(first.storage);reloaded.api.initialize({partial:true,records:[]});assert.deepEqual([...reloaded.api.selectedIds()],rows.slice(0,6).map(r=>r.id));reloaded.api.toggle(rows[0].id);assert.equal(reloaded.api.selectedIds().length,5);assert.equal(JSON.parse(first.storage.get('watch-atlas-comparison-v1-rows')).length,5);});
test('paging finder results preserves selected IDs and hydrated extra specifications',()=>{const {api}=workspace();api.initialize({partial:true,records:[]});api.upsert(rows.slice(0,2));api.toggle(rows[0].id);api.upsert([{...rows[0],extra_specs:[{label:'Manufacturer detail',value:'Documented'}]}]);api.upsert(rows.slice(2),{replace:true});assert.deepEqual([...api.selectedIds()],[rows[0].id]);assert(api.isSelected(rows[0].id));api.toggle(rows[0].id);assert.equal(api.selectedIds().length,0);});
test('an unavailable cached watch is retained as an ID and can always be removed',()=>{const storage=new Map([['watch-atlas-comparison-v1',JSON.stringify({ids:['unavailable']})]]);const {api}=workspace(storage);api.initialize({partial:true,records:[]});assert.deepEqual([...api.selectedIds()],['unavailable']);api.toggle('unavailable');assert.equal(api.selectedIds().length,0);});
