import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {DatabaseSync} from 'node:sqlite';
import M from '../dist/finder-model.js';import C from '../dist/comparison-model.js';import {buildCatalog} from '../tools/build-finder-catalog.mjs';import {compile,createFinderService,sqliteAdapter} from '../backend/finder-service.mjs';
const data=JSON.parse(fs.readFileSync(new URL('../dist/data.json',import.meta.url),'utf8'));const {db,metadata}=buildCatalog(data);
const handle=createFinderService({database:sqliteAdapter(db)});
async function search(params){const response=await handle(new Request('http://localhost/v1/finder/search?'+new URLSearchParams(params)));assert.equal(response.status,200);return response.json();}
const row=(id,props={})=>({id,is_watch:true,brand:'Test',collection_label:'Explorer',specific_model:'Automatic GMT',reference_number:'R'+id,diameter:'40 mm',case_thickness:'9 mm',case_material:'Titanium',movement:'Automatic',movement_family:'Automatic',water_resistance:'10 ATM',features:'Date, GMT',power_reserve:'72 hours',price_value:12000,currency:'USD',source_kind:'Official catalog',...props});
const fixtures=[row('one'),row('two',{case_material:'Ceramic',diameter:'39 mm',price_value:10000}),row('unknown',{diameter:'39 × 41 mm',water_resistance:'',price_value:null,case_material:''}),row('currency',{currency:'INR'}),row('archive',{source_kind:'Archive'}),row('blank',{reference_number:'',specific_model:'No reference',case_material:'',price_value:null,water_resistance:''}),row('boundary',{diameter:'41 mm',price_value:20000})];
const fixtureBuild=buildCatalog({records:fixtures});const fixtureHandle=createFinderService({database:sqliteAdapter(fixtureBuild.db)});
async function fixture(params){const response=await fixtureHandle(new Request('http://localhost/v1/finder/search?'+new URLSearchParams(params)));return {status:response.status,...await response.json()};}

test('six natural-language constraints become precise visible structured filters',()=>{const p=M.parse('Show me automatic titanium GMT watches under 41mm at least 100m and below $20,000.',metadata.facets);assert.equal(p.filters['diameter.lt'],41);assert.equal(p.filters['price.lt'],20000);assert.equal(p.filters['water.min'],100);assert.deepEqual(p.filters.material,['Titanium']);assert.deepEqual(p.filters.complication,['GMT']);assert.deepEqual(p.filters.movement,['Automatic']);assert.equal(p.text,'');});
test('unsupported negation remains literal and cannot imply a positive or unknown attribute',()=>{const p=M.parse('watches without water resistance',metadata.facets);assert.deepEqual(p.filters,{});assert.equal(p.text,'watches without water resistance');assert(p.notes.some(x=>x.includes('Negation')));});
test('vocabulary uses aliases, collection identities, new complication terms and ranges',()=>{assert.deepEqual(M.parse('AP 15500 blue',metadata.facets).filters.brand,['Audemars Piguet']);assert.deepEqual(M.parse('JLC Reverso green',metadata.facets).filters.dial,['Green']);assert.deepEqual(M.parse('VC Overseas',metadata.facets).filters.brand,['Vacheron Constantin']);assert.equal(M.parse('36–40mm manual winding').filters['diameter.min'],36);assert.equal(M.parse('chronograph with 70 hour power reserve').filters['reserve.min'],70);assert.equal(M.parse('dress watch under 10mm thick').filters['thickness.lt'],10);assert.equal(M.parse('100m+').filters['water.min'],100);assert.equal(M.parse('tourbillon under CHF 20k').filters.currency,'CHF');});
test('source normalization rejects ambiguous dimensions, ranges, bare units and battery durations',()=>{for(const diameter of ['39 x 41 mm','38–42 mm','Diagonal: 40 mm','40',''])assert.equal(M.normalize(row('x',{diameter})).diameter,null);assert.equal(M.normalize(row('x',{diameter_metric_eligible:false})).diameter,null);assert.equal(M.normalize(row('x',{power_reserve:'battery life 3 years'})).reserve,null);assert.equal(M.normalize(row('x',{power_reserve:'40–70 hours'})).reserve,null);assert.equal(M.water('Unknown'),null);assert.equal(M.water('not water-resistant'),0);assert.equal(M.water('Waterproof to 1,220 metres / 4,000 feet'),1220);assert.equal(M.normalize(row('x',{production_status:''})).production,null);});
test('dial colors are not taken from hands, markers, subdials or case metal',()=>{assert.deepEqual(M.normalize(row('x',{dial_color:'Appliqued hour-markers, Green, sunray-brushed'})).facets.dial,['Green']);assert.deepEqual(M.normalize(row('x',{dial_color:'Blue dial, pink gold hands, white counters'})).facets.dial,['Blue']);assert.deepEqual(M.normalize(row('x',{dial_color:'White gold hands'})).facets.dial,[]);});
test('explicitly absent complications never become positive facets',async()=>{assert(!M.normalize(row('x',{features:'No date',specific_model:'Black Bay'})).facets.complication.includes('Date'));const n=M.normalize(row('x',{features:'Chronograph without flyback; date: none',specific_model:'Watch'}));assert.deepEqual(n.facets.complication,['Chronograph']);const result=await search({brand:'Tudor',complication:'Date'});assert(result.total>0);assert(result.watches.every(r=>!/^no date$/i.test(r.features)));});
test('same-group OR and cross-group AND use known values only',async()=>{const params=new URLSearchParams();params.append('material','Titanium');params.append('material','Ceramic');params.set('movement','Automatic');params.set('complication','GMT');params.set('diameter.lt','41');params.set('water.min','100');params.set('price.lt','20000');const result=await fixture(params);assert.equal(result.status,200);assert.deepEqual(result.watches.map(r=>r.id).sort(),['one','two']);});
test('strict under excludes the boundary and currencies and price sources stay separate',async()=>{assert.equal((await fixture({q:'titanium under 41mm below $20k'})).total,1);assert.equal((await fixture({material:'Titanium','price.max':20000})).total,2);const result=await fixture({source:'recorded_catalog','price.max':20000});assert.deepEqual(result.watches.map(r=>r.id),['archive']);assert.deepEqual((await fixture({currency:'INR','price.max':20000})).watches.map(r=>r.id),['currency']);});
test('unknown source values never turn into negative facts or satisfy numeric requirements',async()=>{const result=await fixture({'water.min':0});assert(!result.watches.some(r=>r.id==='unknown'));assert.equal((await fixture({material:'Titanium','diameter.max':40,source:'official_retail'})).watches.filter(r=>r.id==='unknown').length,0);});
test('exact reference ranks above prefixes and compact reference lookup remains stable',async()=>{const reference=data.records.find(r=>r.is_watch&&/126710blro-0001/i.test(r.reference_number));const result=await search({q:reference.reference_number});assert.equal(result.watches[0].id,reference.id);const prefix=await search({q:'Rolex 126710BLRO'});assert(prefix.total>=2);assert(prefix.watches.every(r=>/126710blro/i.test(r.reference_number)));const patek=await search({q:'5711'});assert(patek.total>0);assert(patek.watches.every(r=>M.compact(r.reference_number).startsWith('5711')));});
test('blank references cannot match unrelated text and unsupported brands are honest empty states',async()=>{assert.equal((await fixture({q:'unlikely-unmatched-term'})).total,0);assert.equal((await search({q:'VC Overseas'})).total,0);});
test('Pepsi nickname is source-evidenced and no fuzzy fallback contaminates lookup',async()=>{const result=await search({q:'Rolex Pepsi'});assert(result.total>0);assert(result.watches.every(r=>r.brand==='Rolex'&&/Pepsi/.test(r.finder.aliases)));assert.equal((await search({q:'rolexxy pepsixy'})).total,0);});
test('descriptive search and direct structured URL queries return the same IDs',async()=>{const text=await search({q:'automatic GMT under $15,000'});const structured=await search({movement:'Automatic',complication:'GMT','price.lt':15000});assert.equal(text.total,structured.total);assert.deepEqual(text.watches.map(r=>r.id),structured.watches.map(r=>r.id));for(const r of text.watches){assert(r.finder.facets.complication.includes('GMT'));assert.equal(r.currency,'USD');assert(r.price_value<15000);}});
test('all representative existing identities and missing catalog entities are handled',async()=>{for(const [q,expected]of [['JLC Reverso green',true],['Omega Speedmaster Snoopy',true],['Patek perpetual calendar',true],['manual winding tourbillon rose gold',true],['AP 15500 blue',false]]){const r=await search({q});assert.equal(r.total>0,expected,q);}const sparse=await search({q:'thin manual-winding dress watches under $20k'});assert.equal(sparse.total,0);assert(sparse.relaxations.some(x=>x.key==='style'));});
test('URL state round-trips repeated facets, strict thresholds, currency and sort',()=>{const p=new URLSearchParams('material=Titanium&material=Ceramic&diameter.lt=41&price.max=12000&currency=CHF&sort=price-asc&page=3&complicationsMode=any');const s=M.read(p);assert.deepEqual(M.read(M.serialize(s)),s);assert.equal(M.serialize(s).getAll('material').length,2);assert.equal(M.read('diameter.max=&diameter.min=oops').hasOwnProperty('diameter.max'),false);});
test('new price sources can use the same URL, query and currency model',async()=>{fixtureBuild.db.prepare('INSERT INTO finder_prices VALUES (?,?,?,?,?,?)').run('one','market_offer','EUR',9000,'EU','2026-10-05');const state=M.read('source=market_offer&currency=EUR&price.max=10000');assert.equal(M.read(M.serialize(state)).source,'market_offer');const result=await fixture(M.serialize(state));assert.equal(result.total,1);assert.equal(result.watches[0].id,'one');assert.equal(result.watches[0].finder_price.amount,9000);assert.equal(result.watches[0].finder_price.currency,'EUR');assert.equal(result.watches[0].price_value,12000);});
test('multi-complication ALL / ANY is explicit',async()=>{const p=new URLSearchParams('complication=GMT&complication=Chronograph');const all=await search(p);p.set('complicationsMode','any');const any=await search(p);assert(any.total>=all.total);assert(all.watches.every(r=>r.finder.facets.complication.includes('GMT')&&r.finder.facets.complication.includes('Chronograph')));});
test('all sort modes, stable pagination and null-last numeric ordering work',async()=>{for(const sort of Object.keys(M.sorts)){const r=await search({sort});assert.equal(r.watches.length,24);assert(r.total>24);}const a=await search({sort:'brand'}),b=await search({sort:'brand',page:2});assert(!b.watches.some(r=>a.watches.some(x=>x.id===r.id)));const prices=await search({sort:'price-asc'});assert(prices.watches.every((r,i)=>!i||r.price_value>=prices.watches[i-1].price_value));const diameter=await fixture({sort:'diameter-asc'});assert.equal(diameter.watches.at(-1).id,'unknown');});
test('empty states offer measured relaxations without broadening active requirements',async()=>{const result=await fixture({material:'Titanium','diameter.max':10});assert.equal(result.total,0);assert(result.relaxations.some(x=>x.key==='diameter.max'));assert.equal((await fixture({'diameter.min':42,'diameter.max':38})).status,400);});
test('grouped suggestions cover brands, relevant collections, references and structured searches',async()=>{const response=await handle(new Request('http://localhost/v1/finder/suggest?q=Rolex'));const result=await response.json();assert.deepEqual(result.groups.map(g=>g.label),['Brands','Collections','References','Suggested searches']);assert(result.groups.find(g=>g.label==='Collections').items.every(x=>x.state.brand.includes('Rolex')));const related=await (await handle(new Request('http://localhost/v1/finder/suggest?'+new URLSearchParams({q:'JLC Reverso green'})))).json();assert(related.groups.find(g=>g.label==='Collections').items.every(x=>/Reverso/.test(x.label)));});
test('watch hydration is bounded, preserves original data and accepts only GET',async()=>{const id=data.records.find(r=>r.is_watch).id;const response=await handle(new Request('http://localhost/v1/finder/watches?ids='+id));const body=await response.json();assert.equal(body.watches[0].id,id);assert.equal(body.watches[0].description,data.records.find(r=>r.id===id).description);const invalid=await handle(new Request('http://localhost/v1/finder/watches?ids=a,b,c,d,e,f,g'));assert.equal(invalid.status,400);assert.equal((await handle(new Request('http://localhost/v1/finder/search',{method:'POST'}))).status,405);});
test('comparison candidate queries share normalized dimensions and all existing rule operators',async()=>{const sets=[[{field:'diameter',op:'lte',value:'40'}],[{field:'case_material',op:'excludes',value:'Titanium'}],[{field:'diameter',op:'between',value:'36',value2:'40'},{field:'movement_family',op:'equals',value:'Automatic'}],[{field:'price_value',op:'gte',value:'10000',currency:'USD'}],[{field:'extra:Strap description',op:'known',value:''}]];
 for(const rules of sets){const response=await handle(new Request('http://localhost/v1/finder/compare?'+new URLSearchParams({rules:JSON.stringify(rules)})));assert.equal(response.status,200);const result=await response.json();const fields=C.allFields(data.records);assert(result.watches.length<=12);assert(result.watches.every(r=>C.match(r,rules,fields,false).pass),JSON.stringify(rules));}
});
test('SQL values are parameterized and references, facets and numeric constraints are indexed',()=>{const c=compile(M.read(new URLSearchParams({material:"Titanium'); DROP TABLE finder_watches;--",'diameter.max':'40'})),metadata);assert(!c.results.sql.includes('DROP TABLE'));const plans=db.prepare('EXPLAIN QUERY PLAN '+c.results.sql).all(...c.results.params);assert(plans.some(x=>/finder_facets|PRIMARY KEY/.test(x.detail)));const indexes=db.prepare("SELECT name FROM sqlite_master WHERE type='index'").all().map(x=>x.name);assert(indexes.includes('finder_reference'));assert(indexes.includes('finder_price_range'));});
test('rebuilding the derived projection preserves every ID and original source data',()=>{assert.equal(db.prepare('SELECT COUNT(*) AS n FROM finder_watches').get().n,data.records.filter(r=>r.is_watch).length);const copy=structuredClone(data.records[0]);const other=buildCatalog(data,{database:new DatabaseSync(':memory:')});assert.equal(other.metadata.total,metadata.total);assert.deepEqual(data.records[0],copy);other.db.close();});
