'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const source=fs.readFileSync(path.resolve(__dirname,'../dist/price-lookup.js'),'utf8');
const watch={id:'fixture',brand:'IWC',reference_number:'IW659803',price_value:null};
function setup(fetcher,base='https://prices.example'){
 const context={ATLAS_CONFIG:{priceApiBase:base,priceCountry:'us'},document:{querySelectorAll:()=>[]},URL,URLSearchParams,AbortController,setTimeout,clearTimeout,Date,fetch:fetcher};vm.createContext(context);vm.runInContext(source,context);return context.AtlasPrices;
}
function result(patch={}){return {status:'found',country:'us',checked_at:'2026-10-04T12:00:00Z',expires_at:'2099-01-01T00:00:00Z',basis:'Newest dated result among the matching Google results',prices:[{amount:6500,currency:'USD',raw:'USD 6,500',condition:'Pre-owned listing',source_date:'2026-10-01',source_title:'IWC IW659803',source_url:'https://retailer.example/watch'}],...patch};}
test('unconnected price controls provide a direct exact-reference Google search',()=>{const ui=setup(()=>{},'');const html=ui.controls(watch);assert.ok(html.includes('Find reported price on Google'));assert.ok(html.includes('https://www.google.com/search?'));assert.ok(!html.includes('data-price-lookup='));assert.ok(ui.google(watch).includes('IW659803'));});
test('recorded catalog prices do not get a fallback lookup control',()=>{assert.equal(setup(()=>{}).controls({...watch,price_value:6500}),'');});
test('inline lookups send only a catalog ID/country and reuse a fresh result',async()=>{
 let calls=0;const ui=setup(async(url,options)=>{calls++;assert.equal(url,'https://prices.example/v1/price?id=fixture&country=us');assert.equal(options.credentials,'omit');return Response.json(result());});await ui.lookup(watch);await ui.lookup(watch);assert.equal(calls,1);const html=ui.controls(watch);assert.ok(html.includes('USD 6,500'));assert.ok(html.includes('retailer.example/watch'));assert.ok(html.includes('Source dated 2026-10-01'));
});
test('country changes cannot reuse a result from another search country',async()=>{let calls=0;const ui=setup(async()=>{calls++;return Response.json(result());});await ui.lookup(watch);ui.setCountry('in');await ui.lookup(watch);assert.equal(calls,2);});
test('server errors remain useful and retryable with the Google fallback',async()=>{let calls=0;const ui=setup(async()=>{calls++;return calls===1?Response.json({error:'Price search is not connected yet.'},{status:503}):Response.json(result());});await ui.lookup(watch);assert.ok(ui.controls(watch).includes('Search Google directly'));await ui.lookup(watch);assert.equal(calls,2);assert.ok(ui.controls(watch).includes('USD 6,500'));});
test('source strings are escaped and ambiguous currencies remain visibly unspecified',async()=>{const ui=setup(async()=>Response.json(result({prices:[{amount:6500,currency:null,raw:'$6,500',source_title:'<img src=x onerror=alert(1)>',source_url:'javascript:alert(1)',condition:'Unknown'}]})));await ui.lookup(watch);const html=ui.controls(watch);assert.ok(html.includes('Currency unspecified by source'));assert.ok(html.includes('&lt;img'));assert.ok(!html.includes('href="javascript:'));});
test('duplicate browser clicks share the same lookup and successful no-result searches are reusable',async()=>{let calls=0;const ui=setup(async()=>{calls++;await new Promise(resolve=>setTimeout(resolve,10));return Response.json(result({status:'not_found',prices:[]}));});await Promise.all([ui.lookup(watch),ui.lookup(watch)]);await ui.lookup(watch);assert.equal(calls,1);assert.ok(ui.controls(watch).includes('No unambiguous price'));});
